name: "Manual Test Report"
description: "Select a test case and report the result after execution."
title: "[Manual Test] {{ test_id }} by {{ user_name }}"
labels: ["manual-test"]
assignees: []

body:
  - type: input
    id: user_name
    attributes:
      label: "👤 Your Name"
      description: "Enter your GitHub username or handle."
      placeholder: "e.g. @alice123"
    validations:
      required: true

  - type: dropdown
    id: test_id
    attributes:
      label: "🧪 Select a Test"
      description: "Choose the test alias you executed. Review test instructions using the link in the table below."
      options:
        - "Actor_Creation"
        - "Creating_a_Standard_Message"
        - "Creating_Abstract_and_Concrete_Messages"
        - "Creating_Multiple_Messages_for_Actors"
        - "Verify_that_Project_Provider_Features_are_not_Available_when_an_Actor-s_Library_is_Loaded_Directly"
        - "REQUIRES_RT-_Testing_on_RT_Targets"
        - "PPL_Support"
        - "Create_new_instance_of_-Feedback_Evaporative_Cooler-_project"
        - "Create_new_instance_of_-Actor_Framework-_project"
    validations:
      required: true

  - type: dropdown
    id: labview_version
    attributes:
      label: "🧰 LabVIEW Version Used"
      description: "Select the version of LabVIEW you used to run this test."
      options:
        - "LabVIEW 2025 Q1"
        - "LabVIEW 2024 Q3"
        - "LabVIEW 2024 Q1"
        - "LabVIEW 2023 Q3"
        - "LabVIEW 2023 Q1"
        - "LabVIEW 2022 Q3"
        - "LabVIEW 2021"
        - "LabVIEW 2020"
    validations:
      required: true

  - type: dropdown
    id: labview_bitness
    attributes:
      label: "💻 LabVIEW Bitness"
      description: "Choose whether you ran the test in 32-bit or 64-bit LabVIEW."
      options:
        - "32-bit"
        - "64-bit"
    validations:
      required: true

  - type: dropdown
    id: os_used
    attributes:
      label: "🖥️ Operating System"
      description: "Choose which operating system you used for this test run."
      options:
        - "Windows"
        - "Linux"
        - "Real Time (RT)"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📋 Test Metadata Reference

        | Title                                                           | Est. Time | Link                                                                                           |
        |-----------------------------------------------------------------|-----------|------------------------------------------------------------------------------------------------|
        | Actor Creation                                                 | *20 Min*  | [View](https://github.com/ni/actor-framework/blob/develop/Documentation/Test%20Plan/1713129.md) |
        | Creating a Standard Message                                    | *20 Min*  | [View](https://github.com/ni/actor-framework/blob/develop/Documentation/Test%20Plan/1713131.md) |
        | Creating Abstract and Concrete Messages                        | *45 Min*  | [View](https://github.com/ni/actor-framework/blob/develop/Documentation/Test%20Plan/1713132.md) |
        | Creating Multiple Messages for Actors                          | *20 Min*  | [View](https://github.com/ni/actor-framework/blob/develop/Documentation/Test%20Plan/1713133.md) |
        | Project Provider Features not Available                        | *5 Min*   | [View](https://github.com/ni/actor-framework/blob/develop/Documentation/Test%20Plan/1713134.md) |
        | REQUIRES RT - Testing on RT Targets                            | *30 Min*  | [View](https://github.com/ni/actor-framework/blob/develop/Documentation/Test%20Plan/1713135.md) |
        | PPL Support                                                    | *60 Min*  | [View](https://github.com/ni/actor-framework/blob/develop/Documentation/Test%20Plan/1713136.md) |
        | Create new 'Feedback Evaporative Cooler' project               | *10 Min*  | [View](https://github.com/ni/actor-framework/blob/develop/Documentation/Test%20Plan/1713431.md) |
        | Create new 'Actor Framework' project                           | *10 Min*  | [View](https://github.com/ni/actor-framework/blob/develop/Documentation/Test%20Plan/1713432.md) |

  - type: dropdown
    id: test_result
    attributes:
      label: "✅ Test Result"
      description: "What was the result after running the test?"
      options:
        - "Passed"
        - "Failed"
        - "Needs Review"
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: "📝 Notes or Screenshots (optional)"
      description: "Add details, bugs, or screenshots here if needed. (You can paste images directly into the issue.)"
      placeholder: "E.g. Unexpected dialog appeared on step 3..."
    validations:
      required: false
