fields:
  user_name:
    required: true
  test_id:
    required: true
  labview_version:
    required: true
  labview_bitness:
    required: true
  os_used:
    required: true
  test_result:
    required: true
  notes:
    required: false
