name: Manual Test Handler

on:
  issues:
    types: [opened, reopened, edited]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  process-manual-test:
    if: contains(github.event.issue.labels.*.name, 'manual-test')
    runs-on: ubuntu-latest
    env:
      # Personal Access Token with "repo" + "project" scopes
      PROJECTS_TOKEN: ${{ secrets.PROJECTS_TOKEN }}

    steps:
      # --------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # --------------------------------------------------
      - name: Parse manual‑test issue form
        id: parse
        uses: issue-ops/parser@v1.0.0
        with:
          body: ${{ github.event.issue.body }}
          issue-form-template: manual-test-report.yml
          workspace: ${{ github.workspace }}

      # --------------------------------------------------
      - name: Export parser outputs to ENV
        run: |
          echo "NUMID=${{ steps.parse.outputs.numeric_test_id }}" >> $GITHUB_ENV
          echo "EST=${{ steps.parse.outputs.estimate_text }}"       >> $GITHUB_ENV
          echo "LV=${{ steps.parse.outputs.labview_version }}"       >> $GITHUB_ENV
          echo "BIT=${{ steps.parse.outputs.labview_bitness }}"      >> $GITHUB_ENV
          echo "OS=${{ steps.parse.outputs.os_used }}"              >> $GITHUB_ENV
          echo "RESULT=${{ steps.parse.outputs.test_result }}"       >> $GITHUB_ENV
          echo "NOTES=${{ steps.parse.outputs.notes }}"              >> $GITHUB_ENV
          echo "CUR_NUMBER=${{ github.event.issue.number }}"         >> $GITHUB_ENV

      # --------------------------------------------------
      - name: Get previous test's end date
        id: prev
        uses: actions/github-script@v6
        with:
          github-token: ${{ env.PROJECTS_TOKEN }}
          script: |
            const {owner,repo} = context.repo;
            const cur     = parseInt(process.env.CUR_NUMBER,10);
            const author  = context.payload.issue.user.login;
            const query   = `repo:${owner}/${repo} label:manual-test author:${author} in:title "[Manual Test]" sort:created-desc`;

            const res = await github.graphql(`
              query($q:String!){
                search(query:$q,type:ISSUE,first:10){
                  nodes{
                    ... on Issue{
                      number
                      projectItems(first:50){
                        nodes{
                          fieldValues(first:50){
                            nodes{
                              __typename
                              ... on ProjectV2ItemFieldDateValue{
                                date
                                field{ ... on ProjectV2FieldCommon{ name } }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }`, {q: query});

            let prevEnd='';
            for (const n of res.search.nodes){
              if (n.number === cur) continue;
              for (const fv of n.projectItems.nodes.flatMap(i=>i.fieldValues.nodes)){
                if (fv.field?.name === 'End Date' && fv.date){ prevEnd = fv.date; break; }
              }
              if (prevEnd) break;
            }
            core.setOutput('prev_end', prevEnd);
        env:
          CUR_NUMBER: ${{ env.CUR_NUMBER }}

      # --------------------------------------------------
      - name: Update project item fields
        uses: actions/github-script@v6
        with:
          github-token: ${{ env.PROJECTS_TOKEN }}
          script: |
            const {owner,repo} = context.repo;
            const issueNode    = context.payload.issue.node_id;
            const createdDate  = context.payload.issue.created_at.substring(0,19)+'Z';

            // ---------- get existing project items ----------
            const q = await github.graphql(`
              query($id:ID!){
                node(id:$id){
                  ... on Issue{
                    projectItems(first:50){
                      nodes{ id project{id title} }
                    }
                  }
                }
              }`, {id: issueNode});
            let items = q.node.projectItems.nodes;

            // ---------- create project item if none ----------
            if (items.length === 0){
              const pl = await github.graphql(`
                query($o:String!,$r:String!){
                  repository(owner:$o,name:$r){
                    projectsV2(first:1){nodes{id title}}
                  }
                }`, {o: owner, r: repo});
              const proj = pl.repository.projectsV2.nodes[0];
              if (!proj) core.setFailed('No repository project found.');
              const add = await github.graphql(`
                mutation($p:ID!,$c:ID!){
                  addProjectV2ItemById(input:{projectId:$p,contentId:$c}){item{id}}
                }`, {p: proj.id, c: issueNode});
              items = [{id: add.addProjectV2ItemById.item.id, project: proj}];
              core.notice(`Created project item in “${proj.title}”`);
            }

            // ---------- helper to update one field ----------
            async function setField(pid, iid, fid, value){
              await github.graphql(`
                mutation($p:ID!,$i:ID!,$f:ID!,$v:ProjectV2FieldValue!){
                  updateProjectV2ItemFieldValue(input:{
                    projectId:$p,itemId:$i,fieldId:$f,value:$v
                  }){ projectV2Item{id} }
                }`, {p: pid, i: iid, f: fid, v: value});
            }

            // ---------- iterate each project item ----------
            for (const it of items){
              const fv = await github.graphql(`
                query($id:ID!){
                  node(id:$id){
                    ... on ProjectV2Item{
                      fieldValues(first:50){
                        nodes{
                          __typename
                          ... on ProjectV2ItemFieldTextValue{
                            text
                            field{ ... on ProjectV2FieldCommon{ id name } }
                          }
                          ... on ProjectV2ItemFieldDateValue{
                            date
                            field{ ... on ProjectV2FieldCommon{ id name } }
                          }
                          ... on ProjectV2ItemFieldSingleSelectValue{
                            id
                            name
                            field{ ... on ProjectV2FieldCommon{ id name } }
                          }
                        }
                      }
                    }
                  }
                }`, {id: it.id});

              const map = {};
              for (const n of fv.node.fieldValues.nodes){
                map[n.field.name] = {
                  fieldId : n.field.id,
                  type    : n.__typename,
                  node    : n
                };
              }

              // End Date (write once)
              if (map['End Date'] && !map['End Date'].node.date){
                await setField(it.project.id, it.id, map['End Date'].fieldId,
                               {date: createdDate});
              }

              // Start Date (every run if prev exists)
              if (process.env.PREV && map['Start Date']){
                await setField(it.project.id, it.id, map['Start Date'].fieldId,
                               {date: process.env.PREV});
              }

              // plain‑text fields
              const textPairs = [
                ['TestID',            process.env.NUMID],
                ['Estimate',          process.env.EST],
                ['Operating System',  process.env.OS],
                ['LabVIEW Version',   process.env.LV],
                ['LabVIEW Bitness',   process.env.BIT],
                ['Notes',             process.env.NOTES]
              ];
              for (const [fname,val] of textPairs){
                if (map[fname])
                  await setField(it.project.id, it.id, map[fname].fieldId, {text: val});
              }

              // Test Result (single‑select)
              if (map['Test Result'] && map['Test Result'].type === 'ProjectV2ItemFieldSingleSelectValue'){
                await setField(it.project.id, it.id, map['Test Result'].fieldId, {
                  singleSelectOptionId: map['Test Result'].node.id
                });
              }
            }
        env:
          NUMID: ${{ env.NUMID }}
          EST:   ${{ env.EST }}
          LV:    ${{ env.LV }}
          BIT:   ${{ env.BIT }}
          OS:    ${{ env.OS }}
          NOTES: ${{ env.NOTES }}
          PREV:  ${{ steps.prev.outputs.prev_end }}

      # --------------------------------------------------
      - name: Auto‑assign reviewers
        if: always()
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto_assign.yml
